<?php
/**
 * config.inc.php
 *
 * This is the first file loaded in this config directory, among all the other files. These are the base configuration
 * settings which all other configuration files depend on. This file is loaded by the configuration.inc.php file
 * in the directory above.
 *
 * Feel free to make changes as needed.
 */


/**
 * The SERVER_INSTANCE define. This define can be used to change key settings based on whether you
 * are running a development server, staging server, or deployment server. It defaults to dev, but
 * you should run some kind of detection logic to change it depending on your installation.
 *
 * For example, this code changes the setting based on an environment variable:
   if (!defined('SERVER_INSTANCE')) {
	if (isset($_ENV['APP_ENV'])) {
		define('SERVER_INSTANCE', $_ENV['APP_ENV']);
	} elseif (php_sapi_name() === 'cli') {
		define('SERVER_INSTANCE', 'dev');
	} else {
		define('SERVER_INSTANCE', 'prod');
	}

 */

define('SERVER_INSTANCE', 'dev');

/* Constants for Document Root (and Virtual Directories / Subfoldering)
 *
 * IMPORTANT NOTE FOR WINDOWS USERS
 * Please note that all paths should use standard "forward" slashes instead of "backslashes".
 * So windows paths would look like "c:/wwwroot" instead of "c:\wwwroot".
 *
 * Please specify the "Document Root" here.  This is the top level filepath for your web application.
 * If you are on a installation that uses virtual directories, then you must specify that here, as well.
 *
 * For example, if your example web application where http://my.domain.com/index.php points to
 * /home/web/htdocs/index.php, then you must specify:
 *		__DOCROOT__ is defined as '/home/web/htdocs'
 *		(note the leading slash and no ending slash)
 * On Windows, if you have http://my.domain.com/index.php pointing to c:\webroot\files\index.php, then:
 *		__DOCROOT__ is defined as 'c:/webroot/files'
 *		(again, note the leading c:/ and no ending slash)
 *
 * Next, if you are using Virtual Directories, where http://not.my.domain.com/~my_user/index.php
 * (for example) points to /home/my_user/public_html/index.php, then:
 *		__DOCROOT__ is defined as '/home/my_user/public_html'
 *		__VIRTUAL_DIRECTORY__ is defined as '/~my_user'
 *
 * Finally, if you have installed QCubed within a SubDirectory of the Document Root, so for example
 * the QCubed "index.php" page is accessible at http://my.domain.com/qcubeds/qcubed/index.php, then:
 *		__SUBDIRECTORY__ is defined as '/qcubeds/qcubed'
 *		(again, note the leading and no ending slash)
 *
 * In combination with Virtual Directories, if you (for example) have the QCubed "index.php" page
 * accessible at http://not.my.domain.com/~my_user/qcubed/index.php, and the index.php resides at
 * c:\users\my_user\public_html\index.php, then:
 *		__DOCROOT__ is defined as 'c:/users/my_user/public_html'
 *		__VIRTUAL_DIRECTORY__ is defined as '/~my_user'
 *		__SUBDIRECTORY__ is defined as '/qcubed'
 *      /var/www/qcubed/wwwroot
 */

/**
 * Change these to point to the actual locations
 */
switch (SERVER_INSTANCE) {
	case 'dev':
		define ('__DOCROOT__', '/var/www/html'); // absolute path
		define ('__VIRTUAL_DIRECTORY__', ''); // added to URLS
		define ('__SUBDIRECTORY__', '/home/qcubed'); // path from __DOCROOT__ that also appears in URL

		/*
		 * The project directory is where your editable project files go. These include files
		 * that will be generated by the code generator.
		 */
		define ('__PROJECT__', __DOCROOT__ . __SUBDIRECTORY__ . '/project');
		define ('__INCLUDES__', __PROJECT__ . '/includes');
		define ('__EXTERNAL_LIBRARIES__', __DOCROOT__ . __SUBDIRECTORY__ . '/vendor');
		define ('__QCUBED_CORE__', __DOCROOT__ . __SUBDIRECTORY__ . '/vendor/qcubed/qcubed/includes');

	case 'test':
	case 'stage':
	case 'prod':
}

/*
 * If you are using Apache-based mod_rewrite to perform URL rewrites, please specify "apache" here.
 * Otherwise, specify as "none"
 */
define ('__URL_REWRITE__', 'none');

/** The value for QApplication::$EncodingType constant */
define('__APPLICATION_ENCODING_TYPE__', 'UTF-8');

if ((function_exists('date_default_timezone_set')) && (!ini_get('date.timezone')))
	date_default_timezone_set('America/Los_Angeles');

